export const stats = [
  {
    id: 1,
    number: 88.955,
    text: "Already joined us",
  },
  {
    id: 2,
    number: 87.11,
    text: "Happy people with our services",
  },
  {
    id: 3,
    number: 175.32,
    text: "Visited us",
  },
];

export const destinations = [
  {
    id: 1,
    img: [
      "./assets/lagos1.jpg",
      "../../../assets/lagos2.webp",
      "../../../assets/lagos3.png",
      "../../../assets/lagos4.jpg",
    ],
    place: "Algarve",
    title: "The Beauty of Lagos",
    about:
      "Lagos, an ancient marine town, is one of the most visited cities in the Algarve due to its renowned beaches, incredible rock formations, great variety of hotels, bars, restaurants and spirited summer nightlife.",
    color: "",
    addInfo: "Additional information about Algarve goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "The historic centre of Lagos and the Ponta da Piedade",
      "Beach day",
      "Day trip to Sagres and Cabo de São Vicente",
      "Dolphin watching and coastline boat tour or day trip to Burgau",
      "A day at Zoomarine",
      "Day trip to Portimão and Praia da Rocha",
      "Day trip to Praia da Luz, cycle trip or coastal hike",
    ],
    hours: ["08:30", "09:30", "18:30"],
    plan: "",
    continent: "Europe",
    price: 1290,
  },
  {
    id: 2,
    img: [
      "./assets/ny1.webp",
      "../../../assets/ny2.jpg",
      "../../../assets/ny3.jpg",
      "../../../assets/ny4.jpg",
    ],
    place: "New York",
    title: "The Beauty of New York",
    about:
      "New York City is the most populous city in the United States, and the nation's most densely populated of all municipalities (of more than 100,000).",
    color: "",
    addInfo: "Additional information about New York goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Bus Tour & Midtown",
      "Boat Tour & The High Line",
      "Museum & Central Park",
      "Statue of Liberty & Ground Zero",
      "Brooklyn Heights & Lower Manhattan",
      "Helicopter Ride & SoHo",
      "Brooklyn",
    ],
    hours: ["08:30", "09:30", "19:30"],
    plan: "",
    continent: "America",
    price: 4390,
  },
  {
    id: 3,
    img: [
      "./assets/dubai1",
      "../../../assets/dubai2.avif",
      "../../../assets/dubai3.webp",
      "../../../assets/dubai4.jpg",
    ],
    place: "Dubai",
    title: "The Beauty of Dubai",
    about:
      "Dubai is a city of skyscrapers, ports, and beaches, where big business takes place alongside sun-seeking tourism.",
    color: "",
    addInfo: "Additional information about Dubai goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrived at Dubai International Airport",
      "A tour in Old Dubai",
      "Helicopter day",
      "A wonderful view of Dubai from the 143th floor",
      "A day at the beach",
      "Riding a camel on the desert",
      "A goodbye dinner at Couqley French Bistro & Bar",
    ],
    hours: ["09:00", "09:30", "20:00"],
    plan: "",
    continent: "Asia",
    price: 4990,
  },
  {
    id: 4,
    img: [
      "./assets/singapore.jpg",
      "../../../assets/singapore2.jpg",
      "../../../assets/singapore3.avif",
      "../../../assets/singapore4.jpg",
    ],
    place: "Singapore",
    title: "The Beauty of Singapore",
    about: "",
    color: "",
    addInfo: "Additional information about Singapore goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Singapore: Arrival and Night Safari",
      "Day tour of Universal Studio",
      "A day at the Garden by the Bay",
      "A day at the Sentosa Island",
      "Half-day tour of Singapore City",
      "Singapore: Leisure Day",
      "Departure",
    ],
    hours: ["08:30", "09:00", "20:00"],
    plan: "",
    continent: "Asia",
    price: 2900,
  },
  {
    id: 5,
    img: [
      "./assets/switz.jpg",
      "../../../assets/switz2.webp",
      "../../../assets/switz3.webp",
      "../../../assets/switz4.jpg",
    ],
    place: "Switzerland",
    title: "The Beauty of Switzerland",
    about: "",
    color: "",
    addInfo: "Additional information about Switzerland goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrive in Zurich & Explore",
      "Lucerne",
      "Interlaken and Lake Brienz",
      "Lake Thun",
      "Zermatt",
      "Bern",
      "Gruyere & Montreux",
    ],
    hours: ["08:00", "09:00", "20:00"],
    plan: "",
    continent: "Europe",
    price: 1890,
  },
  // Destination 6
  {
    id: 6,
    img: [
      "./assets/italy1.jpg",
      "../../../assets/italy2.webp",
      "../../../assets/italy3.jpg",
      "../../../assets/italy4.jpg",
    ],
    place: "Italy",
    title: "Exploring Italy",
    about:
      "Italy is a country in Southern Europe known for its rich history, art, and cuisine. It is home to iconic landmarks such as the Colosseum, the Leaning Tower of Pisa, and the Vatican City.",
    color: "",
    addInfo: "Additional information about Italy goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrival in Rome and Vatican City Tour",
      "Colosseum and Ancient Rome Tour",
      "Day trip to Florence",
      "Venice City Tour",
      "Amalfi Coast and Pompeii",
      "Leaning Tower of Pisa and Tuscan Countryside",
      "Departure from Rome",
    ],
    hours: ["08:30", "09:00", "20:00"],
    plan: "Experience the cultural wonders of Italy and indulge in its delectable cuisine.",
    continent: "Europe",
    price: 3150,
  },

  // Destination 13
  {
    id: 13,
    img: [
      "./assets/spain1.jpg",
      "../../../assets/spain2.webp",
      "../../../assets/spain3.webp",
      "../../../assets/spain4.jpg",
    ],
    place: "Spain",
    title: "Spanish Delights",
    about:
      "Spain is a country in Europe known for its rich history, diverse culture, and stunning architecture. It offers a wide range of experiences from lively fiestas to tranquil beaches.",
    color: "",
    addInfo: "Additional information about Spain goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrival in Barcelona",
      "Barcelona City Tour",
      "Sagrada Familia and Park Güell",
      "Madrid City Tour",
      "Toledo Day Trip",
      "Seville Alcazar and Cathedral",
      "Departure from Seville",
    ],
    hours: ["08:30", "09:00", "20:00"],
    plan: "Discover the magic and charm of Spain during this delightful 7-day journey.",
    continent: "Europe",
    price: 2790,
  },

  // Destination 14
  {
    id: 14,
    img: [
      "./assets/kenya1.jpg",
      "../../../assets/kenya2.webp",
      "../../../assets/kenya3.jpg",
      "../../../assets/kenya4.webp",
    ],
    place: "Kenya",
    title: "Safari in Kenya",
    about:
      "Kenya is an East African country known for its abundant wildlife and scenic landscapes. It offers thrilling safari experiences and the chance to witness the Great Migration.",
    color: "",
    addInfo: "Additional information about Kenya goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrival in Nairobi",
      "Nairobi National Park",
      "Maasai Mara National Reserve",
      "Tsavo East National Park",
      "Lake Nakuru National Park",
      "Leaning Tower of Pisa and Tuscan Countryside",
      "Departure from Nairobi",
    ],
    hours: ["08:30", "09:00", "20:00"],
    plan: "Embark on an unforgettable safari adventure through the wilderness of Kenya.",
    continent: "Africa",
    price: 3150,
  },
  // Destination 15
  {
    id: 15,
    img: [
      "./assets/china1.jpg",
      "../../../assets/china2.webp",
      "../../../assets/china3.jpg",
      "../../../assets/china4.webp",
    ],
    place: "China",
    title: "China's Wonders",
    about:
      "China is a vast and diverse country known for its ancient history, impressive landmarks, and unique culture. It offers a glimpse into the past while embracing modernity.",
    color: "",
    addInfo: "Additional information about China goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrival in Beijing",
      "Great Wall of China",
      "Forbidden City and Tiananmen Square",
      "Temple of Heaven and Summer Palace",
      "Terracotta Army in Xi'an",
      "Li River Cruise in Guilin",
      "Departure from Shanghai",
    ],
    hours: ["08:30", "09:00", "20:00"],
    plan: "Explore the wonders of China and experience its rich history and culture.",
    continent: "Asia",
    price: 2890,
  },

  // Destination 16
  {
    id: 16,
    img: [
      "./assets/france1.jpg",
      "../../../assets/france2.webp",
      "../../../assets/france3.webp",
      "../../../assets/france4.jpg",
    ],
    place: "France",
    title: "French Romance",
    about:
      "France is a European country known for its romantic ambiance, exquisite cuisine, and iconic landmarks like the Eiffel Tower and Louvre Museum.",
    color: "",
    addInfo: "Additional information about France goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrival in Paris",
      "Paris City Tour",
      "Louvre Museum and Montmartre",
      "Palace of Versailles",
      "French Riviera",
      "Provence Lavender Fields",
      "Departure from Nice",
    ],
    hours: ["08:30", "09:00", "20:00"],
    plan: "Indulge in the romantic charm and cultural splendors of France.",
    continent: "Europe",
    price: 2690,
  },
  // Destination 24
  {
    id: 24,
    img: [
      "./assets/canada1.jpg",
      "../../../assets/canada2.webp",
      "../../../assets/canada3.webp",
      "../../../assets/canada4.jpg",
    ],
    place: "Canada",
    title: "Canadian Charm",
    about:
      "Canada is a vast and diverse country known for its stunning national parks, friendly cities, and abundant wildlife.",
    color: "",
    addInfo: "Additional information about Canada goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrival in Vancouver",
      "Vancouver City Tour",
      "Whistler Adventure",
      "Rocky Mountaineer Train",
      "Banff National Park",
      "Lake Louise",
      "Departure from Calgary",
    ],
    hours: ["08:30", "09:00", "20:00"],
    plan: "Explore the natural wonders and hospitality of Canada on this unforgettable journey.",
    continent: "America",
    price: 3290,
  },

  // Destination 25
  {
    id: 25,
    img: [
      "./assets/norway1.jpg",
      "../../../assets/norway2.webp",
      "../../../assets/norway3.webp",
      "../../../assets/norway4.jpg",
    ],
    place: "Norway",
    title: "Norwegian Nature",
    about:
      "Norway is a breathtaking country known for its majestic fjords, northern lights, and vibrant coastal cities.",
    color: "",
    addInfo: "Additional information about Norway goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrival in Oslo",
      "Oslo City Tour",
      "Bergen and the Fjords",
      "Flam Railway",
      "Geirangerfjord",
      "Tromso and the Arctic",
      "Departure from Oslo",
    ],
    hours: ["08:30", "09:00", "20:00"],
    plan: "Experience the wonders of nature in Norway, from its cities to its fjords.",
    continent: "Europe",
    price: 3390,
  },

  // Destination 26
  {
    id: 26,
    img: [
      "./assets/morocco1.jpg",
      "../../../assets/morocco2.webp",
      "../../../assets/morocco3.webp",
      "../../../assets/morocco4.jpg",
    ],
    place: "Morocco",
    title: "Marvels of Morocco",
    about:
      "Morocco is a vibrant country known for its bustling markets, Sahara Desert, and historic cities like Marrakech and Fez.",
    color: "",
    addInfo: "Additional information about Morocco goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrival in Marrakech",
      "Marrakech City Tour",
      "Atlas Mountains",
      "Sahara Desert Adventure",
      "Ait Ben Haddou",
      "Fez Medina",
      "Departure from Marrakech",
    ],
    hours: ["08:30", "09:00", "20:00"],
    plan: "Discover the rich culture and exotic landscapes of Morocco on this extraordinary journey.",
    continent: "Africa",
    price: 3090,
  },

  // Destination 27
  {
    id: 27,
    img: [
      "./assets/nz1.jpg",
      "../../../assets/nz2.webp",
      "../../../assets/nz3.webp",
      "../../../assets/nz4.jpg",
    ],
    place: "New Zealand",
    title: "New Zealand Enchantment",
    about:
      "New Zealand is a stunning island country known for its breathtaking landscapes, Maori culture, and outdoor adventures.",
    color: "",
    addInfo: "Additional information about New Zealand goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrival in Auckland",
      "Rotorua's Geothermal Wonders",
      "Waitomo Glowworm Caves",
      "Wellington City Tour",
      "Queenstown Adventure",
      "Milford Sound",
      "Departure from Auckland",
    ],
    hours: ["08:30", "09:00", "20:00"],
    plan: "Experience the enchanting beauty and thrilling escapades of New Zealand.",
    continent: "Oceania",
    price: 3490,
  },

  // Destination 28
  {
    id: 28,
    img: [
      "./assets/vietnam1.jpg",
      "../../../assets/vietnam2.webp",
      "../../../assets/vietnam3.webp",
      "../../../assets/vietnam4.jpg",
    ],
    place: "Vietnam",
    title: "Vietnamese Vistas",
    about:
      "Vietnam is a captivating country known for its ancient temples, lush landscapes, and bustling cities like Hanoi and Ho Chi Minh City.",
    color: "",
    addInfo: "Additional information about Vietnam goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrival in Hanoi",
      "Colosseum and Ancient Rome Tour",
      "Hanoi City Tour",
      "Hue's Imperial City",
      "Hoi An Ancient Town",
      "Ho Chi Minh City",
      "Departure from Ho Chi Minh City",
    ],
    hours: ["08:30", "09:00", "20:00"],
    plan: "Immerse yourself in the vibrant culture and scenic wonders of Vietnam.",
    continent: "Asia",
    price: 2990,
  },

  // Destination 29
  {
    id: 29,
    img: [
      "./assets/iceland1.jpg",
      "../../../assets/iceland2.webp",
      "../../../assets/iceland3.webp",
      "../../../assets/iceland4.jpg",
    ],
    place: "Iceland",
    title: "Icelandic Wonders",
    about:
      "Iceland is a land of stunning landscapes, geysers, waterfalls, and the chance to witness the northern lights.",
    color: "",
    addInfo: "Additional information about Iceland goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrival in Reykjavik",
      "Golden Circle",
      "South Coast Adventure",
      "East Fjords",
      "Glacier Lagoon",
      "kureyri and North Iceland",
      "Departure from Reykjavik",
    ],
    hours: ["08:30", "09:00", "20:00"],
    plan: "Experience the wonders of the Land of Fire and Ice, Iceland.",
    continent: "Europe",
    price: 3590,
  },

  // Destination 30
  {
    id: 30,
    img: [
      "./assets/india1.jpg",
      "../../../assets/india2.webp",
      "../../../assets/india3.webp",
      "../../../assets/india4.jpg",
    ],
    place: "India",
    title: "Taj Mahal & Beyond",
    about:
      "India is a country of diverse cultures, magnificent monuments, and bustling cities, including the iconic Taj Mahal.",
    color: "",
    addInfo: "Additional information about India goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrival in Delhi",
      "Delhi City Tour",
      "Agra and the Taj Mahal",
      "Jaipur's Pink City",
      "Udaipur and Lake Pichola",
      "Varanasi's Ghats",
      "Departure from Delhi",
    ],
    hours: ["08:30", "09:00", "20:00"],
    plan: "Discover the magic of India, from its historic treasures to its vibrant traditions.",
    continent: "Asia",
    price: 3290,
  },

  // Destination 31
  {
    id: 31,
    img: [
      "./assets/brazil1.jpg",
      "../../../assets/brazil2.webp",
      "../../../assets/brazil3.webp",
      "../../../assets/brazil4.jpg",
    ],
    place: "Brazil",
    title: "Brazilian Bliss",
    about:
      "Brazil is a country of immense beauty, from the Amazon rainforest to the stunning beaches of Rio de Janeiro.",
    color: "",
    addInfo: "Additional information about Brazil goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrival in Rio de Janeiro",
      "Rio de Janeiro City Tour",
      "Christ the Redeemer",
      "Iguazu Falls",
      "Salvador's Afro-Brazilian Culture",
      "Amazon Rainforest",
      "Departure from Rio de Janeiro",
    ],
    hours: ["08:30", "09:00", "20:00"],
    plan: "Experience the joyful spirit and natural wonders of Brazil.",
    continent: "America",
    price: 3390,
  },

  // Destination 32
  {
    id: 32,
    img: [
      "./assets/kenya1.jpg",
      "../../../assets/kenya2.webp",
      "../../../assets/kenya3.webp",
      "../../../assets/kenya4.jpg",
    ],
    place: "Kenya",
    title: "Kenyan Safari",
    about:
      "Kenya is a safari paradise with vast savannas, abundant wildlife, and the Great Migration in the Maasai Mara.",
    color: "",
    addInfo: "Additional information about Kenya goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrival in Nairobi",
      "Amboseli National Park",
      "Lake Nakuru",
      "Maasai Mara Reserve",
      "Maasai Mara Hot Air Balloon Safari",
      "Tsavo National Park",
      "Departure from Nairobi",
    ],
    hours: ["08:30", "09:00", "20:00"],
    plan: "Embark on an unforgettable safari adventure in the heart of Africa, Kenya.",
    continent: "Africa",
    price: 3590,
  },

  // Destination 33
  {
    id: 33,
    img: [
      "./assets/france1.jpg",
      "../../../assets/france2.webp",
      "../../../assets/france3.webp",
      "../../../assets/france4.jpg",
    ],
    place: "France",
    title: "French Riviera",
    about:
      "France's French Riviera is famous for its glamorous cities, beautiful coastline, and rich cultural heritage.",
    color: "",
    addInfo: "Additional information about France goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrival in Nice",
      "French Riviera Beaches",
      "Monaco and Eze",
      "Venice City Tour",
      "Provence Countryside",
      "Marseille and Aix-en-Provence",
      "Departure from Nice",
    ],
    hours: ["08:30", "09:00", "20:00"],
    plan: "Experience the elegance and beauty of the French Riviera.",
    continent: "Europe",
    price: 3390,
  },
  // Destination 34
  {
    id: 34,
    img: [
      "./assets/thailand1.jpg",
      "../../../assets/thailand2.webp",
      "../../../assets/thailand3.webp",
      "../../../assets/thailand4.jpg",
    ],
    place: "Thailand",
    title: "Island Paradise - Thailand",
    about:
      "Thailand is a tropical paradise known for its stunning beaches, ornate temples, and vibrant street markets.",
    color: "",
    addInfo: "Additional information about Thailand goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrival in Bangkok",
      "Bangkok City Tour",
      "Ayutthaya Temples",
      "Phuket Island",
      "Phi Phi Islands",
      "Krabi and Railay Beach",
      "Departure from Bangkok",
    ],
    hours: ["08:30", "09:00", "20:00"],
    plan: "Indulge in the beauty and relaxation of Thailand's islands and culture.",
    continent: "Asia",
    price: 3190,
  },

  // Destination 35
  {
    id: 35,
    img: [
      "./assets/australia1.jpg",
      "../../../assets/australia2.webp",
      "../../../assets/australia3.webp",
      "../../../assets/australia4.jpg",
    ],
    place: "Australia",
    title: "Aussie Adventures",
    about:
      "Australia is a vast and diverse country known for its stunning landscapes, unique wildlife, and vibrant cities.",
    color: "",
    addInfo: "Additional information about Australia goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrival in Sydney",
      "Sydney City Tour",
      "Day trip to Florence",
      "Blue Mountains",
      "Uluru (Ayers Rock)",
      "Melbourne and Phillip Island",
      "Departure from Sydney",
    ],
    hours: ["08:30", "09:00", "20:00"],
    plan: "Embark on exciting adventures in the land down under, Australia.",
    continent: "Australia",
    price: 3590,
  },

  // Destination 36
  {
    id: 36,
    img: [
      "./assets/spain1.jpg",
      "../../../assets/spain2.webp",
      "../../../assets/spain3.webp",
      "../../../assets/spain4.jpg",
    ],
    place: "Spain",
    title: "Spanish Serenity",
    about:
      "Spain is a country known for its passionate culture, historic landmarks, and beautiful beaches.",
    color: "",
    addInfo: "Additional information about Spain goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrival in Madrid",
      "Madrid City Tour",
      "Toledo Day Trip",
      "Barcelona's Gaudi Architecture",
      "Park Guell and La Sagrada Familia",
      "Valencia's Arts and Sciences",
      "Departure from Madrid",
    ],
    hours: ["08:30", "09:00", "20:00"],
    plan: "Experience the charm and vibrancy of Spain on this serene journey.",
    continent: "Europe",
    price: 3290,
  },
  // Destination 38
  {
    id: 38,
    img: [
      "./assets/safrica1.jpg",
      "../../../assets/safrica2.webp",
      "../../../assets/safrica3.webp",
      "../../../assets/safrica4.jpg",
    ],
    place: "South Africa",
    title: "Safari in South Africa",
    about:
      "South Africa is a wildlife haven with diverse landscapes, bustling cities, and the opportunity to go on safari.",
    color: "",
    addInfo: "Additional information about South Africa goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrival in Cape Town",
      "Cape Town City Tour",
      "Cape Peninsula",
      "Winelands",
      "Johannesburg and Soweto",
      "Kruger National Park Safari",
      "Departure from Cape Town",
    ],
    hours: ["08:30", "09:00", "20:00"],
    plan: "Embark on an exciting safari adventure in the heart of South Africa.",
    continent: "Africa",
    price: 3590,
  },

  // Destination 39
  {
    id: 39,
    img: [
      "./assets/germany1.jpg",
      "../../../assets/germany2.webp",
      "../../../assets/germany3.webp",
      "../../../assets/germany4.jpg",
    ],
    place: "Germany",
    title: "German Getaway",
    about:
      "Germany is a country of rich history, charming towns, and vibrant cities, as well as the famous Oktoberfest celebration.",
    color: "",
    addInfo: "Additional information about Germany goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrival in Berlin",
      "Berlin's Historic Sites",
      "Potsdam Day Trip",
      "Dresden's Baroque Beauty",
      "Munich and Oktoberfest",
      "Neuschwanstein Castle",
      "Departure from Frankfurt",
    ],
    hours: ["08:30", "09:00", "20:00"],
    plan: "Experience the cultural wonders and festivities of Germany.",
    continent: "Europe",
    price: 3290,
  },

  // Destination 40
  {
    id: 40,
    img: [
      "./assets/mexico1.jpg",
      "../../../assets/mexico2.webp",
      "../../../assets/mexico3.webp",
      "../../../assets/mexico4.jpg",
    ],
    place: "Mexico",
    title: "Mexican Magic",
    about:
      "Mexico is a country of vibrant colors, ancient ruins, stunning beaches, and delicious cuisine.",
    color: "",
    addInfo: "Additional information about Mexico goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrival in Mexico City",
      "Mexico City's Historic Center",
      "Teotihuacan Pyramids",
      "Oaxaca and Monte Alban",
      "Playa del Carmen",
      "Chichen Itza",
      "Departure from Cancun",
    ],
    hours: ["08:30", "09:00", "20:00"],
    plan: "Experience the magic and diversity of Mexico.",
    continent: "America",
    price: 3090,
  },
];
