export const stats = [
  {
    id: 1,
    number: 88.955,
    text: "Already joined us",
  },
  {
    id: 2,
    number: 87.11,
    text: "Happy people with our services",
  },
  {
    id: 3,
    number: 175.32,
    text: "Visited us",
  },
];

export const destinations = [
  {
    id: 1,
    img: [
      "./assets/lagos1.jpg",
      "../../../assets/lagos2.webp",
      "../../../assets/lagos3.png",
      "../../../assets/lagos4.jpg",
    ],
    place: "Algarve",
    title: "The Beauty of Lagos",
    about:
      "Lagos, an ancient marine town, is one of the most visited cities in the Algarve due to its renowned beaches, incredible rock formations, great variety of hotels, bars, restaurants and spirited summer nightlife.",
    color: "",
    addInfo: "Additional information about Algarve goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: ["The historic centre of Lagos and the Ponta da Piedade", "Beach day", "Day trip to Sagres and Cabo de São Vicente", "Dolphin watching and coastline boat tour or day trip to Burgau", "A day at Zoomarine", "Day trip to Portimão and Praia da Rocha", "Day trip to Praia da Luz, cycle trip or coastal hike"],
    hours: ["08:30", "09:30", "18:30"],
    plan: "",
    continent: "Europe",
  },
  {
    id: 2,
    img: [
      "./assets/ny1.webp",
      "../../../assets/ny2.jpg",
      "../../../assets/ny3.jpg",
      "../../../assets/ny4.jpg",
    ],
    place: "New York",
    title: "The Beauty of New York",
    about:
      "New York City is the most populous city in the United States, and the nation's most densely populated of all municipalities (of more than 100,000).",
    color: "",
    addInfo: "Additional information about New York goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: ["Bus Tour & Midtown", "Boat Tour & The High Line", "Museum & Central Park", "Statue of Liberty & Ground Zero", "Brooklyn Heights & Lower Manhattan", "Helicopter Ride & SoHo", "Brooklyn"],
    hours: ["08:30", "09:30", "19:30"],
    plan: "",
    continent: "America",
  },
  {
    id: 3,
    img: [
      "./assets/dubai1",
      "../../../assets/dubai2.avif",
      "../../../assets/dubai3.webp",
      "../../../assets/dubai4.jpg",
    ],
    place: "Dubai",
    title: "The Beauty of Dubai",
    about:
      "Dubai is a city of skyscrapers, ports, and beaches, where big business takes place alongside sun-seeking tourism.",
    color: "",
    addInfo: "Additional information about Dubai goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: [
      "Arrived at Dubai International Airport",
      "A tour in Old Dubai",
      "Helicopter day",
      "A wonderful view of Dubai from the 143th floor",
      "A day at the beach",
      "Riding a camel on the desert",
      "A goodbye dinner at Couqley French Bistro & Bar",
    ],
    hours: ["09:00", "09:30", "20:00"],
    plan: "",
    continent: "Asia",
  },
  {
    id: 4,
    img: [
      "./assets/singapore.jpg",
      "../../../assets/singapore2.jpg",
      "../../../assets/singapore3.avif",
      "../../../assets/singapore4.jpg",
    ],
    place: "Singapore",
    title: "The Beauty of Singapore",
    about: "",
    color: "",
    addInfo: "Additional information about Singapore goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: ["Singapore: Arrival and Night Safari", "Day tour of Universal Studio", "A day at the Garden by the Bay", "A day at the Sentosa Island", "Half-day tour of Singapore City", "Singapore: Leisure Day", "Departure"],
    hours: ["08:30", "09:00", "20:00"],
    plan: "",
    continent: "Asia",
  },
  {
    id: 5,
    img: [
      "./assets/switz.jpg",
      "../../../assets/switz2.webp",
      "../../../assets/switz3.webp",
      "../../../assets/switz4.jpg",
    ],
    place: "Switzerland",
    title: "The Beauty of Switzerland",
    about: "",
    color: "",
    addInfo: "Additional information about Switzerland goes here...",
    day: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    tour: ["Arrive in Zurich & Explore", "Lucerne", "Interlaken and Lake Brienz", "Lake Thun", "Zermatt", "Bern", "Gruyere & Montreux"],
    hours: ["08:00", "09:00", "20:00"],
    plan: "",
    continent: "Europe",
  },
];
